"""Writes a shell script that pops open Preview.app on flagged images, grouped by directory, so
you can eyeball whether a re-orientation actually made sense. See docs/how-it-works.md.
"""

import itertools
from collections import defaultdict
from pathlib import Path

from orientation_correction import divider


def _group_by_dir(paths: list[Path]) -> dict[Path, list[Path]]:
    by_dir: dict[Path, list[Path]] = defaultdict(list)
    for p in paths:
        by_dir[p.parent].append(p)
    return by_dir


def _write_section(
    lines: list[str],
    label: str,
    short_label: str,
    paths: list[Path],
    divider_dir: Path,
    divider_index: itertools.count,
) -> bool:
    by_dir = _group_by_dir(paths)
    if not by_dir:
        return False

    lines.append(f"# {label} ({len(paths)} file(s))")
    for directory in sorted(by_dir):
        filenames = sorted(p.name for p in by_dir[directory])

        divider_path = divider_dir / f"divider-{next(divider_index):03d}.png"
        divider.write_divider(
            divider_path, category=short_label, directory=directory, file_count=len(filenames)
        )

        lines.append(f'export DIR="{directory}"')
        quoted = " ".join(f'"$DIR/{name}"' for name in filenames)
        lines.append(f'open -a preview "{divider_path}" {quoted}')
    lines.append("")
    return True


def write_preview_links(
    output_path: Path,
    *,
    corrected: list[Path],
    would_correct: list[Path],
    low_confidence: list[Path],
    divider_dir: Path,
) -> None:
    """corrected: files actually rotated this run (--apply). would_correct: files that would be
    rotated if re-run with --apply (dry-run candidates). low_confidence: predicted as needing
    rotation but below --min-confidence, so left untouched either way -- flagged for a human to
    decide.

    divider_dir: where to write one small divider image per (category, directory) group --
    opened as the first image in each Preview.app window/thumbnail strip, so it's obvious which
    category and directory the images that follow belong to. Created only if there's at least
    one group to write."""
    lines: list[str] = [
        "#!/usr/bin/env bash",
        "# Auto-generated by orientation-correct. Opens flagged images in Preview.app, grouped",
        "# by directory, for a manual sanity check that the re-orientation makes sense. Each",
        "# group's first image is a divider naming its category and directory.",
        "set -euo pipefail",
        "",
    ]

    divider_index = itertools.count(1)
    wrote_any = False
    wrote_any |= _write_section(
        lines, "Corrected", "Corrected", corrected, divider_dir, divider_index
    )
    wrote_any |= _write_section(
        lines,
        "Would be corrected (dry-run -- re-run with --apply once these look right)",
        "Would be corrected (dry-run)",
        would_correct,
        divider_dir,
        divider_index,
    )
    wrote_any |= _write_section(
        lines,
        "Low confidence -- NOT auto-corrected, please review manually",
        "Low confidence -- not auto-corrected",
        low_confidence,
        divider_dir,
        divider_index,
    )

    if not wrote_any:
        lines.append("# Nothing flagged this run.")

    output_path.write_text("\n".join(lines) + "\n")
    output_path.chmod(0o755)


def write_review_checklist(
    output_path: Path,
    *,
    corrected: list[Path],
    would_correct: list[Path],
    revert_command: str,
) -> bool:
    """A plain-text checklist of every file rotated this run (or that would be, in dry-run mode):
    one absolute path per line. Delete the line for every file that's actually fine, leaving
    only the false positives, then feed the trimmed file to `revert_command` -- see
    docs/how-it-works.md#reviewing-and-reverting-false-positives. Returns False (and writes
    nothing) if there's nothing to review."""
    flagged = sorted({*corrected, *would_correct})
    if not flagged:
        return False

    lines = [
        "# orientation-correct review checklist.",
        "#",
        "# One line per file rotated this run (or that would be, in dry-run mode). Open the",
        "# matching preview-links-*.sh to eyeball each one in Preview.app, then DELETE the line",
        "# for every file that's actually fine -- leave only the false positives.",
        "#",
        "# Once only the wrong ones are left, run:",
        f"#   {revert_command}",
        "",
        *(str(p) for p in flagged),
    ]
    output_path.write_text("\n".join(lines) + "\n")
    return True
