"""Writes a shell script that pops open Preview.app on flagged images, grouped by directory, so
you can eyeball whether a re-orientation actually made sense. See docs/how-it-works.md.
"""

import itertools
from collections import defaultdict
from pathlib import Path

from orientation_correction import divider


def _group_by_dir(paths: list[Path]) -> dict[Path, list[Path]]:
    by_dir: dict[Path, list[Path]] = defaultdict(list)
    for p in paths:
        by_dir[p.parent].append(p)
    return by_dir


def _write_section(
    lines: list[str],
    label: str,
    short_label: str,
    paths: list[Path],
    divider_dir: Path,
    divider_index: itertools.count,
) -> bool:
    by_dir = _group_by_dir(paths)
    if not by_dir:
        return False

    lines.append(f"# {label} ({len(paths)} file(s))")
    for directory in sorted(by_dir):
        filenames = sorted(p.name for p in by_dir[directory])

        divider_path = divider_dir / f"divider-{next(divider_index):03d}.png"
        divider.write_divider(
            divider_path, category=short_label, directory=directory, file_count=len(filenames)
        )

        lines.append(f'export DIR="{directory}"')
        quoted = " ".join(f'"$DIR/{name}"' for name in filenames)
        lines.append(f'open -a preview "{divider_path}" {quoted}')
        lines.append('sleep 1;')
    lines.append("")
    return True


_CATEGORIES = [
    ("corrected", "Corrected", "Corrected"),
    (
        "would-correct",
        "Would be corrected (dry-run -- re-run with --apply once these look right)",
        "Would be corrected (dry-run)",
    ),
    (
        "low-confidence",
        "Low confidence -- NOT auto-corrected, please review manually",
        "Low confidence -- not auto-corrected",
    ),
]


def write_preview_links(
    output_dir: Path,
    *,
    corrected: list[Path],
    would_correct: list[Path],
    low_confidence: list[Path],
    divider_dir: Path,
) -> list[Path]:
    """Writes one preview-links script per non-empty category -- corrected, would_correct,
    low_confidence -- rather than a single combined script, so each category opens in its own
    Preview.app session instead of all three being interleaved into one long scroll. corrected:
    files actually rotated this run (--apply). would_correct: files that would be rotated if
    re-run with --apply (dry-run candidates). low_confidence: predicted as needing rotation but
    below --min-confidence, so left untouched either way -- flagged for a human to decide.

    output_dir is expected to be a run's own timestamped directory (see cli.py), so filenames
    here don't need their own timestamp suffix.

    divider_dir: where to write one small divider image per (category, directory) group --
    opened as the first image in each Preview.app window/thumbnail strip, so it's obvious which
    category and directory the images that follow belong to. Created only if there's at least
    one group to write.

    Returns the list of script paths actually written (categories with nothing flagged get no
    file at all, rather than an empty placeholder -- with one file per category, there's no
    single natural place left to hang a "nothing flagged" placeholder on)."""
    divider_index = itertools.count(1)
    by_category = {
        "corrected": corrected,
        "would-correct": would_correct,
        "low-confidence": low_confidence,
    }
    written: list[Path] = []

    for slug, label, short_label in _CATEGORIES:
        lines: list[str] = [
            "#!/usr/bin/env bash",
            f"# Auto-generated by orientation-correct. Opens '{label}' images in Preview.app,",
            "# grouped by directory, for a manual sanity check. Each group's first image is a",
            "# divider naming its category and directory.",
            "set -euo pipefail",
            "",
        ]

        wrote_section = _write_section(
            lines, label, short_label, by_category[slug], divider_dir, divider_index
        )
        if not wrote_section:
            continue

        output_dir.mkdir(parents=True, exist_ok=True)
        output_path = output_dir / f"preview-links-{slug}.sh"
        output_path.write_text("\n".join(lines) + "\n")
        output_path.chmod(0o755)
        written.append(output_path)

    return written


def write_review_checklist(
    output_path: Path,
    *,
    corrected: list[Path],
    would_correct: list[Path],
    revert_command: str,
) -> bool:
    """A plain-text checklist of every file rotated this run (or that would be, in dry-run mode):
    one absolute path per line. Delete the line for every file that's actually fine, leaving
    only the false positives, then feed the trimmed file to `revert_command` -- see
    docs/how-it-works.md#reviewing-and-reverting-false-positives. Returns False (and writes
    nothing) if there's nothing to review."""
    flagged = sorted({*corrected, *would_correct})
    if not flagged:
        return False

    lines = [
        "# orientation-correct review checklist.",
        "#",
        "# One line per file rotated this run (or that would be, in dry-run mode). Open the",
        "# matching preview-links-*.sh to eyeball each one in Preview.app, then DELETE the line",
        "# for every file that's actually fine -- leave only the false positives.",
        "#",
        "# Once only the wrong ones are left, run:",
        f"#   {revert_command}",
        "",
        *(str(p) for p in flagged),
    ]
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines) + "\n")
    return True
