"""Writes a shell script that pops open Preview.app on flagged images, grouped by directory, so
you can eyeball whether they're really blurry/over/under-exposed. One script per (issue category,
run mode) pair -- e.g. preview-links-blurry-would-quarantine.sh -- rather than one combined
script, so each opens in its own Preview.app session instead of every category being interleaved
into one long scroll. Categories are dynamic (an image can match more than one, e.g. "dark+light")
rather than a fixed set, since CleanVision's blurry/dark/light checks are independent of each
other.
"""

import itertools
from collections import defaultdict
from pathlib import Path

from image_quality_detector import divider

_MODE_LABELS = {
    "quarantined": "Quarantined",
    "would-quarantine": (
        "Would be quarantined (dry-run -- re-run with --apply once these look right)"
    ),
}


def _category_label(category_key: str) -> str:
    """'blurry' -> 'Blurry'; 'dark+light' -> 'Dark + Light'."""
    return " + ".join(part.capitalize() for part in category_key.split("+"))


def _group_by_dir(paths: list[Path]) -> dict[Path, list[Path]]:
    by_dir: dict[Path, list[Path]] = defaultdict(list)
    for p in paths:
        by_dir[p.parent].append(p)
    return by_dir


def _write_section(
    lines: list[str],
    label: str,
    short_label: str,
    paths: list[Path],
    divider_dir: Path,
    divider_index: itertools.count,
) -> bool:
    by_dir = _group_by_dir(paths)
    if not by_dir:
        return False

    lines.append(f"# {label} ({len(paths)} file(s))")
    for directory in sorted(by_dir):
        filenames = sorted(p.name for p in by_dir[directory])

        divider_path = divider_dir / f"divider-{next(divider_index):03d}.png"
        divider.write_divider(
            divider_path, category=short_label, directory=directory, file_count=len(filenames)
        )

        lines.append(f'export DIR="{directory}"')
        quoted = " ".join(f'"$DIR/{name}"' for name in filenames)
        lines.append(f'open -a preview "{divider_path}" {quoted}')
        lines.append("sleep 2;")
    lines.append("")
    return True


def write_preview_links(
    output_dir: Path,
    *,
    mode: str,
    by_category: dict[str, list[Path]],
    divider_dir: Path,
) -> list[Path]:
    """Writes one preview-links script per non-empty category in `by_category` -- the paths
    passed in should already be the "current" location of each file: the original path in
    dry-run mode (nothing moved), or the quarantine path in apply mode (the file no longer
    exists at its original path).

    mode: "quarantined" or "would-quarantine" -- both the run's outcome and, combined with each
    category key, the script's filename.

    output_dir is expected to be a run's own timestamped directory (see cli.py), so filenames
    here don't need their own timestamp suffix.

    divider_dir: where to write one small divider image per (category, directory) group --
    opened as the first image in each Preview.app window/thumbnail strip, so it's obvious which
    category and directory the images that follow belong to. Created only if there's at least
    one group to write.

    Returns the list of script paths actually written (categories with nothing flagged get no
    file at all)."""
    mode_label = _MODE_LABELS[mode]
    divider_index = itertools.count(1)
    written: list[Path] = []

    for category_key in sorted(by_category):
        paths = by_category[category_key]
        category_label = _category_label(category_key)
        label = f"{category_label} -- {mode_label}"
        short_label = f"{category_label} -- {mode_label.split(' (')[0]}"

        lines: list[str] = [
            "#!/usr/bin/env bash",
            f"# Auto-generated by image-quality-detect. Opens '{label}' images in Preview.app,",
            "# grouped by directory, for a manual sanity check. Each group's first image is a",
            "# divider naming its category and directory.",
            "set -euo pipefail",
            "",
        ]

        wrote_section = _write_section(lines, label, short_label, paths, divider_dir, divider_index)
        if not wrote_section:
            continue

        output_dir.mkdir(parents=True, exist_ok=True)
        output_path = output_dir / f"preview-links-{category_key}-{mode}.sh"
        output_path.write_text("\n".join(lines) + "\n")
        output_path.chmod(0o755)
        written.append(output_path)

    return written


def write_review_checklist(
    output_path: Path,
    *,
    flagged: list[Path],
    revert_command: str,
) -> bool:
    """A plain-text checklist of every file flagged this run: one absolute *original* path per
    line (even in apply mode, where the file has already moved to quarantine -- revert.py knows
    how to find it from there). Delete the line for every file that's genuinely bad, leaving
    only the false positives, then feed the trimmed file to `revert_command`. Returns False (and
    writes nothing) if there's nothing to review."""
    entries = sorted(set(flagged))
    if not entries:
        return False

    lines = [
        "# image-quality-detect review checklist.",
        "#",
        "# One line per file flagged this run (quarantined if --apply was used, otherwise just",
        "# a dry-run candidate). Open the matching preview-links-*.sh to eyeball each one in",
        "# Preview.app, then DELETE the line for every file that's genuinely blurry/over/under-",
        "# exposed -- leave only the false positives.",
        "#",
        "# Once only the wrong ones are left, run:",
        f"#   {revert_command}",
        "",
        *(str(p) for p in entries),
    ]
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines) + "\n")
    return True
